Repository Orange-OpenSource/OCast-JVM, pull requests merged in 2019-09, with the labels that each got.

#65 Fix setMediaTrack
  sdk/src/main/kotlin/org/ocast/sdk/core/models/Media.kt
Labels: bug

#62 Logs
  README.md
  mediaroute/src/main/kotlin/org/ocast/mediaroute/OCastMediaRouteProvider.kt
  sdk/src/main/kotlin/org/ocast/sdk/core/DeviceCenter.kt
  sdk/src/main/kotlin/org/ocast/sdk/core/ReferenceDevice.kt
  sdk/src/main/kotlin/org/ocast/sdk/core/WebSocket.kt
  sdk/src/main/kotlin/org/ocast/sdk/core/models/OCastError.kt
  sdk/src/main/kotlin/org/ocast/sdk/core/utils/OCastLog.kt
  sdk/src/main/kotlin/org/ocast/sdk/dial/DialClient.kt
  sdk/src/main/kotlin/org/ocast/sdk/dial/models/DialError.kt
  sdk/src/main/kotlin/org/ocast/sdk/discovery/DeviceDiscovery.kt
  sdk/src/main/kotlin/org/ocast/sdk/discovery/UDPSocket.kt
  sdk/src/main/kotlin/org/ocast/sdk/discovery/UpnpClient.kt
Labels: enhancement

#67 Fix readme
  README.md
Labels: documentation

#71 Linebreak matcher
  sdk/src/main/kotlin/org/ocast/sdk/discovery/models/SsdpMessage.kt
Labels: bug

#70 Fix a bug where discovery state is wrong after an unexpected stop
  sdk/src/main/kotlin/org/ocast/sdk/discovery/DeviceDiscovery.kt
  sdk/src/test/kotlin/org/ocast/sdk/discovery/DeviceDiscoveryTest.kt
Labels: bug

#75 Fix logs
  README.md
  sdk/src/main/kotlin/org/ocast/sdk/core/ReferenceDevice.kt
  sdk/src/main/kotlin/org/ocast/sdk/core/WebSocket.kt
  sdk/src/main/kotlin/org/ocast/sdk/core/utils/OCastLog.kt
  sdk/src/main/kotlin/org/ocast/sdk/dial/DialClient.kt
  sdk/src/main/kotlin/org/ocast/sdk/discovery/UDPSocket.kt
  sdk/src/main/kotlin/org/ocast/sdk/discovery/UpnpClient.kt
Labels: bug

#74 Fix bugs in reference device
  sdk/src/main/kotlin/org/ocast/sdk/core/ReferenceDevice.kt
Labels: bug
