Repository Orange-OpenSource/OCast-JVM, pull requests merged in 2019-06, with the labels that each got.

#5 Add Travis CI
  .travis.yml
  OCast/build.gradle
Labels: continuous integration

#4 Add an XMLParser class
  OCast/src/main/java/org/ocast/common/utils/XMLParser.kt
  OCast/src/main/java/org/ocast/discovery/DialClient.kt
  OCast/src/test/java/org/ocast/common/utils/XMLParserTest.kt
Labels: enhancement

#1 Android MediaRoute Helper
  .idea/gradle.xml
  OCast/src/main/java/org/ocast/core/Device.java
  mediaroute/build.gradle
  mediaroute/proguard-rules.pro
  mediaroute/src/androidTest/java/org/ocast/mediaroute/FakeDeviceMediaRouteProvider.kt
  mediaroute/src/androidTest/java/org/ocast/mediaroute/OCastMediaRouteHelperTest.kt
  mediaroute/src/main/AndroidManifest.xml
  mediaroute/src/main/java/org/ocast/mediaroute/AndroidUIThreadCallbackWrapper.java
  mediaroute/src/main/java/org/ocast/mediaroute/OCastMediaRouteHelper.kt
  mediaroute/src/main/java/org/ocast/mediaroute/OCastMediaRouteProvider.kt
  mediaroute/src/main/java/org/ocast/mediaroute/models/MediaRouteDevice.kt
  settings.gradle
Labels: enhancement

#2 Add DIAL requests
  OCast/src/main/java/org/ocast/common/OkHttpExt.kt
  OCast/src/main/java/org/ocast/common/utils/XMLParser.kt
  OCast/src/main/java/org/ocast/dial/DialClient.kt
  OCast/src/main/java/org/ocast/dial/models/DialApplication.kt
  OCast/src/main/java/org/ocast/dial/models/DialError.kt
  OCast/src/main/java/org/ocast/discovery/DeviceDiscovery.kt
  OCast/src/main/java/org/ocast/discovery/UpnpClient.kt
  OCast/src/test/java/org/ocast/common/HttpClientTest.kt
  OCast/src/test/java/org/ocast/common/StringExt.kt
  OCast/src/test/java/org/ocast/common/SynchronizedFunction.kt
  OCast/src/test/java/org/ocast/dial/DialClientTest.kt
  OCast/src/test/java/org/ocast/discovery/DeviceDiscoveryTest.kt
  OCast/src/test/java/org/ocast/discovery/DialClientTest.kt
  OCast/src/test/java/org/ocast/discovery/SsdpMessageTest.kt
  OCast/src/test/java/org/ocast/discovery/UpnpClientTest.kt
Labels: enhancement

#6 Bugs fixes
  OCast/src/main/java/org/ocast/common/utils/XMLParser.kt
  OCast/src/main/java/org/ocast/core/Device.java
  OCast/src/main/java/org/ocast/core/OCastCenter.kt
  OCast/src/main/java/org/ocast/core/ReferenceDevice.kt
  OCast/src/main/java/org/ocast/core/WebSocketProvider.kt
  OCast/src/main/java/org/ocast/core/models/OCastError.kt
  OCast/src/main/java/org/ocast/core/utils/OCastLog.kt
  OCast/src/main/java/org/ocast/discovery/DeviceDiscovery.kt
  OCast/src/test/java/org/ocast/discovery/DeviceDiscoveryTest.kt
Labels: bug

#9 Fix bugs
  OCast/build.gradle
  OCast/src/main/java/org/ocast/core/Device.java
  OCast/src/main/java/org/ocast/core/ReferenceDevice.kt
  OCast/src/main/java/org/ocast/core/WebSocketProvider.kt
  OCast/src/main/java/org/ocast/core/models/OCastError.kt
  OCast/src/main/java/org/ocast/core/models/Settings.kt
  OCast/src/main/java/org/ocast/discovery/DeviceDiscovery.kt
  build.gradle
  mediaroute/build.gradle
  mediaroute/src/main/java/org/ocast/mediaroute/AndroidUIThreadCallbackWrapper.java
  sampleDesktopKotlin/build.gradle
  sampleDesktopKotlin/src/main/java/org/ocast/sample/desktop/AppKotlin.kt
Labels: bug

#8 Use lambdas instead of strings when logging
  OCast/src/main/java/org/ocast/core/ReferenceDevice.kt
  OCast/src/main/java/org/ocast/core/WebSocketProvider.kt
  OCast/src/main/java/org/ocast/core/utils/OCastLog.kt
  OCast/src/main/java/org/ocast/discovery/DeviceDiscovery.kt
  OCast/src/main/java/org/ocast/discovery/UpnpClient.kt
  sampleDesktopJava/src/main/java/org/ocast/sample/desktop/AppJava.java
  sampleDesktopKotlin/src/main/java/org/ocast/sample/desktop/AppKotlin.kt
Labels: enhancement
